// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novin.Arayeshyar.Backend.Infrastructure.Database;

#nullable disable

namespace Novin.Arayeshyar.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ArayeshyarDB))]
    [Migration("20231108184639_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Novin.Arayeshyar.Backend.Core.Entities.BarberOwner", b =>
                {
                    b.Property<string>("Mobilenumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BarberShopname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mobilenumber");

                    b.ToTable("BarberOwners");
                });

            modelBuilder.Entity("Novin.Arayeshyar.Backend.Core.Entities.Customer", b =>
                {
                    b.Property<string>("Mobilenumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mobilenumber");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Novin.Arayeshyar.Backend.Core.Entities.SistemAdmin", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobilenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("SistemAdmins");
                });
#pragma warning restore 612, 618
        }
    }
}
